MagicFinger/MagicFinger-war/src/java/manageBeans/crud/CursoController.java
package manageBeans.crud;

import entity.Alumno;
import entity.AlumnosDelCurso;
import entity.Curso;
import entity.Profesor;
import entity.ProfesoresPorCurso;
import entity.ProfesoresPorDepartamento;
import manageBeans.crud.util.JsfUtil;
import manageBeans.crud.util.PaginationHelper;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import manageBeans.LoginSessionMB;
import sessionBeans.AlumnoFacadeLocal;
import sessionBeans.CursoFacadeLocal;
import sessionBeans.ProfesorFacadeLocal;
import sessionBeans.ProfesoresPorDepartamentoFacadeLocal;

@Named("cursoController")
@RequestScoped
public class CursoController implements Serializable {
    @EJB
    private ProfesorFacadeLocal profesorFacade;
    @EJB
    private ProfesoresPorDepartamentoFacadeLocal profesoresPorDepartamentoFacade;
    @EJB
    
    private AlumnoFacadeLocal alumnoFacade;
    private Curso current;
    private DataModel items = null;
    @EJB
    private CursoFacadeLocal ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    @Inject
    LoginSessionMB session;
    private List<Alumno> listAlumno = new ArrayList<>();
    private List<String> listAlumnoSelecionados = new ArrayList<>();
    private List<Profesor> listProfesor = new ArrayList<>();
    private List<String> listProfesorSelecionados = new ArrayList<>();
    @Inject
    AlumnosDelCursoController alumnosdelcurso;
    @Inject
    ProfesoresPorCursoController profesoresporcurso;
    public CursoController() {
    }
    @PostConstruct
    public void init(){
        listAlumno = alumnoFacade.BuscarPorIdUniversidad(session.getIdUniversidad());
        List<ProfesoresPorDepartamento> profePorDepa = profesoresPorDepartamentoFacade.BuscarPorIdUniversidad(session.getIdUniversidad());
            List lista = new ArrayList();
            for (ProfesoresPorDepartamento object : profePorDepa) {
                if(object.getProfesor()!=null && !lista.contains(object.getProfesor())){
                    lista.add(object.getProfesor()); 
                }
            }
            listProfesor = lista;
    }
    public Curso getSelected() {
        if (current == null) {
            current = new Curso();
            current.setCursoPK(new entity.CursoPK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private CursoFacadeLocal getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(200) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView(Curso vari) {
        current = vari;
        //selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Curso();
        current.setCursoPK(new entity.CursoPK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            current.getCursoPK().setTipIdTipoAsignatura(current.getTipoAsignatura().getIdTipoAsignatura());
            current.getCursoPK().setAsiIdAsignatura(current.getAsignatura().getIdAsignatura());
            current.getCursoPK().setSemIdFecha(current.getSemestre().getIdFecha());
            ejbFacade.create(current);
            AlumnosDelCurso alumnosCurso = new AlumnosDelCurso();
            alumnosCurso.setAlumnosDelCursoPK(new entity.AlumnosDelCursoPK());
            alumnosCurso.setCurso(current);
            ProfesoresPorCurso profesorCurso = new ProfesoresPorCurso();
            profesorCurso.setProfesoresPorCursoPK(new entity.ProfesoresPorCursoPK());
            profesorCurso.setCurso(current);
            for (String object : listAlumnoSelecionados) {
                alumnosCurso.setAlumno(alumnoFacade.find(Integer.parseInt(object)));
                alumnosdelcurso.setCurrent(alumnosCurso);
                alumnosdelcurso.create();
            }
            for (String object : listProfesorSelecionados) {
                profesorCurso.setProfesor(profesorFacade.find(Integer.parseInt(object)));
                profesoresporcurso.setCurrent(profesorCurso);
                profesoresporcurso.create();
            }
            
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Curso creado", "Se ha creado una Curso correctamente"));
            return prepareList();
        } catch (Exception e) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Curso no creado", "Lo sentimos, los datos que ingresó ya existen"));
            return null;
        }
    }

    public String prepareEdit(Curso var) {
        current = var;
        //selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            current.getCursoPK().setTipIdTipoAsignatura(current.getTipoAsignatura().getIdTipoAsignatura());
            current.getCursoPK().setAsiIdAsignatura(current.getAsignatura().getIdAsignatura());
            current.getCursoPK().setSemIdFecha(current.getSemestre().getIdFecha());
            getFacade().edit(current);
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Curso actualizado", "Se ha actualizado correctamente"));
            return "View";
        } catch (Exception e) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Curso no actualizado", "Lo sentimos, los datos que ingresó ya existen"));
            return null;
        }
    }

    public String destroy(Curso valor) {
        current = valor;
        //selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Curso eliminado", "Se ha eliminado una Curso"));
        } catch (Exception e) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "ERROR: Curso no eliminado", "Lo sentimos, intentelo mas tarde"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = new ListDataModel(ejbFacade.BuscarPorIdUniversidad(session.getIdUniversidad()));
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.BuscarPorIdUniversidad(session.getIdUniversidad()), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.BuscarPorIdUniversidad(session.getIdUniversidad()), true);
    }

    public Curso getCurso(entity.CursoPK id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Curso.class)
    public static class CursoControllerConverter implements Converter {

        private static final String SEPARATOR = "#";

MagicFinger/MagicFinger-war/web/administrador/curso/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Agregar Curso</title>
        <link href="/MagicFinger-war/faces/resources/css/default.css" rel="stylesheet" type="text/css" />
        <link href="/MagicFinger-war/faces/resources/css/cssLayout.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="/MagicFinger-war/faces/jsfcrud.css" />

    </h:head>
    <h:body>
        <div id="top" style="display: inline-block; text-align: center">
            <div id="logo" style="display: inline-block; float:left">
                <h:form>
                 <h:commandLink action="/faces/administrador/index.xhtml">
                            <img src="/MagicFinger-war/faces/img/MagicFinger.png" style="padding: 5px" height="40" width="150" />
                 </h:commandLink>
                </h:form>
            </div>
            <div id="hora" style="display: inline-block;vertical-align: middle; margin-top: 17px">
                <p:clock pattern="dd.MM.yy HH.mm" mode="server"/>
            </div>
            <div style="display: inline-block;float: right;margin-top:10px">
                <h:form id="form" prependId="false">
                    <div style="display: inline-block;vertical-align: middle"><p:outputLabel value="#{loginSessionMB.usuario}"/></div>
                    
                    <div style="display: inline-block;width: 50px;vertical-align: middle">
                        <p:commandLink action="#{loginMB.logout()}" value="Cerrar sesión">
                            <p:confirm header="Confirmación" message="¿Desea cerrar sesión?" icon="ui-icon-alert" />  
                        </p:commandLink>
                        <p:confirmDialog global="true" showEffect="explode" hideEffect="explode">  
                            <p:commandButton style="margin-left:10%;" value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"/>  
                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>       
                        </p:confirmDialog>
                    </div>
                </h:form>
            </div>
        </div>      
        <div class="center_content">
            <h1 style="margin-bottom: 20px;font-family: -webkit-pictograph;">
                    <span>Agregar curso</span> 
                    <span style="float: right"> #{postLoginMB.nombreUniversidad} <span style="font: menu">
                        <h:outputLink value="/MagicFinger-war/faces/administrador/index.xhtml" >
                             [Cambiar]
                        </h:outputLink>
                        </span> 
                    </span> 
             </h1>
            <h:form id="form2" prependId="false"><p:growl id="grow1" showDetail="true" />
                <div style="text-align:center">
                   
                  <div style="text-align: left; display: inline-block;width: 100%; margin-bottom: 20px;" >
                    <p:menubar style="width: 75%;vertical-align: middle;display: inline-block">  
                    <p:menuitem value="Alumnos" url="/faces/administrador/alumno/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:submenu label="Profesores" icon="ui-icon-bullet" >
                        <p:menuitem value="Gestión Profesores" url="/faces/administrador/profesor/List.xhtml" icon="ui-icon-bullet" /> 
                        <p:menuitem value="Profesores por Dpto." url="/faces/administrador/profesoresPorDepartamento/List.xhtml" icon="ui-icon-bullet" /> 
                    </p:submenu>
                    <p:submenu label="Cursos" icon="ui-icon-bullet">  
                        <p:menuitem value="Gestión de cursos" url="/faces/administrador/curso/List.xhtml" icon="ui-icon-bullet" /> 
                        <p:menuitem value="Asignaturas" url="/faces/administrador/asignatura/List.xhtml" icon="ui-icon-bullet" />   
                        <p:menuitem value="Tipo de asignaturas" url="/faces/administrador/tipoAsignatura/List.xhtml" icon="ui-icon-bullet" />   
                        <p:menuitem value="Bloques" url="/faces/administrador/bloqueClase/List.xhtml" icon="ui-icon-bullet" />   
                        <p:menuitem value="Alumnos por curso" url="/faces/administrador/alumnosDelCurso/List.xhtml" icon="ui-icon-bullet" />
                        <p:menuitem value="Profesores por curso" url="/faces/administrador/profesoresPorCurso/List.xhtml" icon="ui-icon-bullet" />
                    </p:submenu>
                    <p:menuitem value="Facultades" url="/faces/administrador/facultad/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:menuitem value="Departamentos" url="/faces/administrador/departamento/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:menuitem value="Planes de estudios" url="/faces/administrador/malla/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:menuitem value="Carreras" url="/faces/administrador/carrera/List.xhtml" icon="ui-icon-bullet" /> 
               </p:menubar>
                    </div>
                     <div id="agregar" style="display: inline-block;width: 100%;">
                    <img src="/MagicFinger-war/faces/img/advertencia.png" height="24" width="26" style="vertical-align: middle"/>
                    <p style="vertical-align: middle;display: inline-block;text-align: center">
                        Para agregar un curso, debe completar los siguientes datos:
                    </p>
                    
                    </div>
                    <div style="display:inline-block;border-width: 1px ;border-radius: 10px ;border-style: dashed; border-color: gray; width: 600px;text-align: center;margin-top: 10px ">
                        <h:panelGrid columns="2" style="margin: 0 auto; padding: 10px;">
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="Asignatura:" for="asignatura" />
                            </h4>
                            <p:selectOneMenu style="vertical-align: center" id="asignatura" value="#{cursoController.selected.asignatura}"  required="true" requiredMessage="Debe seleccionar una asignatura">
                                <f:selectItems value="#{asignaturaController.itemsAvailableSelectOne}"/>
                            </p:selectOneMenu>
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="Semestre:" for="semestre" />
                            </h4>
                            <p:selectOneMenu style="vertical-align: center" id="semestre" value="#{cursoController.selected.semestre}"  required="true" requiredMessage="Debe selecionar un semestre">
                                <f:selectItems value="#{semestreController.itemsAvailableSelectOne}"/>
                            </p:selectOneMenu>
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="Tipo de asignatura:" for="tipoAsignatura" />
                            </h4>
                            <p:selectOneMenu style="vertical-align: center" id="tipoAsignatura" value="#{cursoController.selected.tipoAsignatura}"  required="true" requiredMessage="Debe seleccionar un tipo de asignatura">
                                <f:selectItems value="#{tipoAsignaturaController.itemsAvailableSelectOne}"/>
                            </p:selectOneMenu>
                            
                            
                            
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="Porcentaje de aprobación:" for="porcentajeAprobacion" />
                            </h4>
                            <p:spinner id="porcentajeAprobacion" value="#{cursoController.selected.porcentajeAprobacion}" min="0" max="100" required="true" requiredMessage="Debe ingresar un porcentaje entre 0 y 100"/> 
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="Atrasados después de (min):" for="termino" />
                            </h4>
                            <p:spinner id="termino" value="#{cursoController.selected.termino}" min="0" max="90" required="true" requiredMessage="Debe ingresar el tiempo de atrasados entre 0 y 90 min."/> 
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="Alumnos" for="alumnos"  />
                            </h4>
                            <p:selectCheckboxMenu value="#{cursoController.listAlumnoSelecionados}" id="alumnos" label="Alumnos" filter="true" filterMatchMode="startsWith" panelStyle="width:220px">  
                                <f:selectItems value="#{cursoController.listAlumno}"  var="alu" itemLabel="#{alu.nombre} #{alu.apellidop} #{alu.apellidom}" itemValue="#{alu.idAlumno}"/>  
                            </p:selectCheckboxMenu>
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="Profesores" for="profesores"  />
                            </h4>
                            <p:selectCheckboxMenu value="#{cursoController.listProfesorSelecionados}" id="profesores" label="Profesores" filter="true" filterMatchMode="startsWith" panelStyle="width:220px">  
                                <f:selectItems value="#{cursoController.listProfesor}"  var="pro" itemLabel="#{pro.nombre} #{pro.apellidop} #{pro.apellidom}" itemValue="#{pro.idProfesor}"/>  
                            </p:selectCheckboxMenu>
                            
                           
                            
                            
                        </h:panelGrid>
                        <h:commandLink style="display: inline-block; margin-right: 25px" action="#{cursoController.create}">
                            <img src="/MagicFinger-war/faces/img/ok.png" width="38" height="32" style="margin: 0 auto;display:block"/>
                            <h:outputLabel> Guardar curso</h:outputLabel>
                        </h:commandLink>
                        <h:commandLink style="display: inline-block;" action="#{cursoController.prepareList}" immediate="true">
                            <img src="/MagicFinger-war/faces/img/atras.png" width="38" height="32" style="margin: 0 auto;display:block"/>
                            <h:outputLabel>Volver</h:outputLabel>
                        </h:commandLink>
                        <br></br><br></br>
                    </div>
                </div>
            </h:form>
        </div>
    </h:body>
</html>

MagicFinger/MagicFinger-war/web/administrador/curso/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Editar Curso</title>
        <link href="/MagicFinger-war/faces/resources/css/default.css" rel="stylesheet" type="text/css" />
        <link href="/MagicFinger-war/faces/resources/css/cssLayout.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="/MagicFinger-war/faces/jsfcrud.css" />

    </h:head>
    <h:body>
        <div id="top" style="display: inline-block; text-align: center">
            <div id="logo" style="display: inline-block; float:left">
                <h:form>
                 <h:commandLink action="/faces/administrador/index.xhtml">
                            <img src="/MagicFinger-war/faces/img/MagicFinger.png" style="padding: 5px" height="40" width="150" />
                 </h:commandLink>
                </h:form>
            </div>
            <div id="hora" style="display: inline-block;vertical-align: middle; margin-top: 17px">
                <p:clock pattern="dd.MM.yy HH.mm" mode="server"/>
            </div>
            <div style="display: inline-block;float: right;margin-top:10px">
                
                <h:form id="form" prependId="false">
                    <div style="display: inline-block;vertical-align: middle"><p:outputLabel value="#{loginSessionMB.usuario}"/></div>
                    
                    <div style="display: inline-block;width: 50px;vertical-align: middle">
                        <p:commandLink action="#{loginMB.logout()}" value="Cerrar sesión">
                            <p:confirm header="Confirmación" message="¿Desea cerrar sesión?" icon="ui-icon-alert" />  
                        </p:commandLink>
                        <p:confirmDialog global="true" showEffect="explode" hideEffect="explode">  
                            <p:commandButton style="margin-left:10%;" value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"/>  
                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>       
                        </p:confirmDialog>
                    </div>
                </h:form>
            </div>
        </div>      
        <div class="center_content">

            <h:form><p:growl id="grow1" showDetail="true" />
                <h1 style="margin-bottom: 20px;font-family: -webkit-pictograph;">
                <span>Editar curso</span> 
                <span style="float: right"> #{postLoginMB.nombreUniversidad} <span style="font: menu">
                    <h:outputLink value="/MagicFinger-war/faces/administrador/index.xhtml" >
                         [Cambiar]
                    </h:outputLink>
                    </span> 
                </span> 
                </h1>
                <div style="text-align:center">
                   <div style="text-align: left; display: inline-block;width: 100%; margin-bottom: 20px;" >
                        <p:menubar style="width: 75%;vertical-align: middle;display: inline-block">  
                    <p:menuitem value="Alumnos" url="/faces/administrador/alumno/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:submenu label="Profesores" icon="ui-icon-bullet" >
                        <p:menuitem value="Gestión Profesores" url="/faces/administrador/profesor/List.xhtml" icon="ui-icon-bullet" /> 
                        <p:menuitem value="Profesores por Dpto." url="/faces/administrador/profesoresPorDepartamento/List.xhtml" icon="ui-icon-bullet" /> 
                    </p:submenu>
                    <p:submenu label="Cursos" icon="ui-icon-bullet">  
                        <p:menuitem value="Gestión de cursos" url="/faces/administrador/curso/List.xhtml" icon="ui-icon-bullet" /> 
                        <p:menuitem value="Asignaturas" url="/faces/administrador/asignatura/List.xhtml" icon="ui-icon-bullet" />   
                        <p:menuitem value="Tipo de asignaturas" url="/faces/administrador/tipoAsignatura/List.xhtml" icon="ui-icon-bullet" />   
                        <p:menuitem value="Bloques" url="/faces/administrador/bloqueClase/List.xhtml" icon="ui-icon-bullet" />   
                        <p:menuitem value="Alumnos por curso" url="/faces/administrador/alumnosDelCurso/List.xhtml" icon="ui-icon-bullet" />
                        <p:menuitem value="Profesores por curso" url="/faces/administrador/profesoresPorCurso/List.xhtml" icon="ui-icon-bullet" />
                    </p:submenu>
                    <p:menuitem value="Facultades" url="/faces/administrador/facultad/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:menuitem value="Departamentos" url="/faces/administrador/departamento/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:menuitem value="Planes de estudios" url="/faces/administrador/malla/List.xhtml" icon="ui-icon-bullet" /> 
                    <p:menuitem value="Carreras" url="/faces/administrador/carrera/List.xhtml" icon="ui-icon-bullet" /> 
               </p:menubar>
                    </div>
                   <div id="editar" style="display: inline-block;width: 100%;">
                        <img src="/MagicFinger-war/faces/img/advertencia.png" height="32" width="36" style="vertical-align: middle"/>
                        <p style="vertical-align: middle;display: inline-block;text-align: center">
                            Para editar el curso, puede modificar los siguientes campos:
                        </p>
                    </div>
                    <div style="display:inline-block;border-width: 1px ;border-radius: 10px ;border-style: dashed; border-color: gray; width: 600px;text-align: center;margin-top: 10px ">
                        <h:panelGrid columns="2" style="margin: 0 auto; padding: 10px;">
                           
                            <h4><p:outputLabel value="Porcentaje de aprobación:" for="porcentajeAprobacion" /></h4>
                            <p:inputText id="porcentajeAprobacion" value="#{cursoController.selected.porcentajeAprobacion}" />
                            <h4><p:outputLabel value="Atrasados después de (min):" for="termino" /></h4>
                            <p:inputText id="termino" value="#{cursoController.selected.termino}" />
                            <h4><p:outputLabel value="#{bundle.EditCursoLabel_asignatura}" for="asignatura" /></h4>
                            <h:inputHidden id="asignatura" value="#{cursoController.selected.asignatura}" />
                               
                            <h:inputHidden id="semestre" value="#{cursoController.selected.semestre}" />
                            <h:inputHidden id="tipoAsignatura" value="#{cursoController.selected.tipoAsignatura}" />
                        </h:panelGrid>
                        <h:commandLink style="display: inline-block; margin-right: 25px" action="#{cursoController.update}">
                            <img src="/MagicFinger-war/faces/img/ok.png" width="38" height="32" style="margin: 0 auto;display:block"/>
                            <p:outputLabel>Guardar cambios</p:outputLabel>
                        </h:commandLink>
                        <h:commandLink style="display: inline-block;" action="#{cursoController.prepareList}" immediate="true">
                            <img src="/MagicFinger-war/faces/img/atras.png" width="38" height="32" style="margin: 0 auto;display:block"/>
                            <p:outputLabel>Volver</p:outputLabel>
                        </h:commandLink>
                        <br></br><br></br>
                    </div>
                </div>
            </h:form>
        </div>
    </h:body>
</html>
