MagicFinger/MagicFinger-war/src/java/manageBeans/GruposMB.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package manageBeans;

import com.sun.org.apache.xerces.internal.parsers.IntegratedParserConfiguration;
import entity.AlumnosDelCurso;
import entity.Grupos;
import entity.Profesor;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.TransferEvent;
import org.primefaces.model.DualListModel;
import sessionBeans.AlumnosDelCursoFacadeLocal;
import sessionBeans.GruposFacadeLocal;

/**
 *
 * @author lol
 */
@Named(value = "gruposMB")
@RequestScoped
public class GruposMB {
    @EJB
    private GruposFacadeLocal gruposFacade;
    @EJB
    private AlumnosDelCursoFacadeLocal alumnosDelCursoFacade;

    private gruposDataModel ListaGrupoData;
    private Grupos grupoSeleccionado;
    private Profesor profesor;
    private List<Grupos> ListGrupos;
    private List<AlumnosDelCurso> listaIntegrante;
     private DualListModel<AlumnosDelCurso> asignar;
     private DualListModel<String> asignarString;
     
    public GruposMB() {
      
    }
    @Inject
    LoginSessionMB profesorLogin;
    @Inject
    GrupoConversation conversation;
    @PostConstruct
    public void init() {
        grupoSeleccionado = conversation.getGruposelecionado();
        System.out.println("grupo selecionado actual" + grupoSeleccionado);
        
      //  grupoSeleccionado = profesorLogin.get;
        asignar = new DualListModel<>();
        ListGrupos = new ArrayList<>();
        profesor = profesorLogin.getProfesor();
        if (profesor != null) {
            List<Grupos> GruposAux = gruposFacade.findAll();
            for (Grupos grupos : GruposAux) {
                if(grupos.getCurso().equals(profesorLogin.getCurso())){
                    ListGrupos.add(grupos);
                }
            }
            ListaGrupoData = new gruposDataModel(ListGrupos);
        }
        if(grupoSeleccionado!=null){
            System.out.println("voy a recargar la volva");
            listarIntegrantes();
            }
    }
    
    public void listarIntegrantes(){
    conversation.setGruposelecionado(grupoSeleccionado);
        System.out.println("se ha seteado el grupo: " + grupoSeleccionado);
        List<AlumnosDelCurso> aux = alumnosDelCursoFacade.BuscarPorIdUniversidad(profesorLogin.getIdUniversidad());
        List<AlumnosDelCurso> aux2 = new ArrayList<>();

        for (AlumnosDelCurso alumnosDelCurso : aux) {
            if(alumnosDelCurso.getCurso().equals(profesorLogin.getCurso())){
                aux2.add(alumnosDelCurso);
            }
        }
        List<AlumnosDelCurso> aux3 = new ArrayList<>();
        listaIntegrante = new ArrayList<>();
        for (AlumnosDelCurso alumnosDelCurso : aux2) {
            if(alumnosDelCurso.getGruIdGrupo()==null){
                aux3.add(alumnosDelCurso);
            }else if(alumnosDelCurso.getGruIdGrupo().equals(grupoSeleccionado)){
                listaIntegrante.add(alumnosDelCurso);
            }
           
        }
        if(!listaIntegrante.isEmpty()){
            asignar = new DualListModel<>(aux3, listaIntegrante);
        }else{
            asignar = new DualListModel<>(aux3, new ArrayList<AlumnosDelCurso>());
        }
        
    }
    public void onRowSelect(SelectEvent event) {
        FacesMessage msg = new FacesMessage("Grupo Seleccionado", grupoSeleccionado.toString());
        listarIntegrantes();
        
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
    public void actualizar(){
         
    }
    public void onTransfer(TransferEvent event) {  

        for (Iterator<AlumnosDelCurso> it = asignar.getTarget().iterator(); it.hasNext();) {
            
            String alumno = it.next()+"";
            System.out.println("Alumno Integrante: "+alumno);
            List<AlumnosDelCurso> Alumno = alumnosDelCursoFacade.BuscarPorIdAlumno(Integer.parseInt(alumno));
            for (AlumnosDelCurso alumnosDelCurso : Alumno) {
                if(alumnosDelCurso.getGruIdGrupo()==null && alumnosDelCurso.getCurso().equals(profesorLogin.getCurso())){
                alumnosDelCurso.setGruIdGrupo(grupoSeleccionado);
                alumnosDelCursoFacade.edit(alumnosDelCurso);
                System.out.println("GRupo: "+alumnosDelCurso.getGruIdGrupo());
            }
            }
            
        }
        for (Iterator<AlumnosDelCurso> it = asignar.getSource().iterator(); it.hasNext();) {
           String alumno = it.next()+"";
            System.out.println("Alumno Disponible: "+alumno);
           List<AlumnosDelCurso> Alumno = alumnosDelCursoFacade.BuscarPorIdAlumno(Integer.parseInt(alumno));
            for (AlumnosDelCurso alumnosDelCurso : Alumno) {
                if(alumnosDelCurso.getGruIdGrupo()!=null && alumnosDelCurso.getCurso().equals(profesorLogin.getCurso())){
                alumnosDelCurso.setGruIdGrupo(null);
                alumnosDelCursoFacade.edit(alumnosDelCurso);
                System.out.println("GRupo: "+alumnosDelCurso.getGruIdGrupo());
            }
            }
        }
        FacesMessage msg = new FacesMessage();  
        msg.setSeverity(FacesMessage.SEVERITY_INFO);  
        msg.setSummary("Actualizado");  
          
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }  
    

    public void setListaGrupoData(gruposDataModel ListaGrupoData) {
        this.ListaGrupoData = ListaGrupoData;
    }

    public Grupos getGrupoSeleccionado() {
        return grupoSeleccionado;
    }

    public void setGrupoSeleccionado(Grupos grupoSeleccionado) {
        this.grupoSeleccionado = grupoSeleccionado;
    }

    public Profesor getProfesor() {
        return profesor;
    }

    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    public List<Grupos> getListGrupos() {
        return ListGrupos;
    }

    public void setListGrupos(List<Grupos> ListGrupos) {
        this.ListGrupos = ListGrupos;
    }

    public LoginSessionMB getProfesorLogin() {
        return profesorLogin;
    }

    public void setProfesorLogin(LoginSessionMB profesorLogin) {
        this.profesorLogin = profesorLogin;
    }

    public List<AlumnosDelCurso> getListaIntegrante() {
        return listaIntegrante;
    }

    public void setListaIntegrante(List<AlumnosDelCurso> listaIntegrante) {
        this.listaIntegrante = listaIntegrante;
    }

    public DualListModel<AlumnosDelCurso> getAsignar() {
        return asignar;
    }

    public void setAsignar(DualListModel<AlumnosDelCurso> asignar) {
        this.asignar = asignar;
    }

    public DualListModel<String> getAsignarString() {
        return asignarString;
    }

    public void setAsignarString(DualListModel<String> asignarString) {
        this.asignarString = asignarString;
    }

    public gruposDataModel getListaGrupoData() {
        return ListaGrupoData;
    }


    
}

MagicFinger/MagicFinger-war/src/java/manageBeans/crud/GruposController.java
package manageBeans.crud;

import entity.AlumnosDelCurso;
import entity.Grupos;
import java.io.IOException;
import manageBeans.crud.util.JsfUtil;
import manageBeans.crud.util.PaginationHelper;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import manageBeans.GrupoConversation;
import manageBeans.LoginSessionMB;
import sessionBeans.GruposFacadeLocal;

@Named("gruposController")
@RequestScoped
public class GruposController implements Serializable {

    private Grupos current;
    private DataModel items = null;
    @EJB
    private GruposFacadeLocal ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    @Inject
    private LoginSessionMB session;
    @Inject
    private GrupoConversation conversationGrupo;
    public GruposController() {
    }

    public Grupos getSelected() {
        if (current == null) {
            current = new Grupos();
            selectedItemIndex = -1;
        }
        return current;
    }

    private GruposFacadeLocal getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(200) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView(Grupos vari) {
        current = vari;
        //selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }
    public void redireccionar(String pagina){
        System.out.println("intenta redireccionar");
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
       try {
           System.out.println("va a redireccionar ctm");
           externalContext.redirect(externalContext.getRequestContextPath() + pagina);
           
       }
       catch (IOException e) {
           System.out.println("error redirect");
           System.out.println(e.getMessage());
       }
    }
    public void envioDatosGrupo(){
        System.out.println("antes convesation");
        conversationGrupo.beginConversation();
        System.out.println("despues conversation");
        redireccionar("/faces/profesor/grupos/grupos.xhtml?cid=".concat(this.conversationGrupo.getConversation().getId()));
        System.out.println("redirigir");
    }
    public String prepareCreate() {
        current = new Grupos();
        selectedItemIndex = -1;
        return "Create";
    }

    public void create() {
        try {
            current.setCurso(session.getCurso());
            current.setAlumnosDelCursoList(new ArrayList<AlumnosDelCurso>());
            getFacade().create(current);
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Grupos creado", "Se ha creado una Grupos correctamente"));
            envioDatosGrupo();
        } catch (Exception e) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Grupo no creado", "Lo sentimos, los datos que ingresó ya existen"));
        }
    }

    public String prepareEdit(Grupos var) {
        current = var;
       // selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public void update() {
        try {
            getFacade().edit(current);
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Grupos actualizado", "Se ha actualizado correctamente"));
            envioDatosGrupo();
        } catch (Exception e) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
           
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Grupo no actualizado", "Lo sentimos, los datos que ingresó ya existen"));
        }
    }

    public void destroy(Grupos valor) {
        current = valor;
       // selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        envioDatosGrupo();
    }

    public void destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            envioDatosGrupo();
        } else {
            // all items were removed - go back to list
            recreateModel();
            envioDatosGrupo();
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "Grupos eliminado", "Se ha eliminado una Grupos"));
        } catch (Exception e) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "ERROR: Grupos no eliminado", "Lo sentimos, intentelo mas tarde"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Grupos getGrupos(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Grupos.class)
    public static class GruposControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            GruposController controller = (GruposController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "gruposController");
            return controller.getGrupos(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Grupos) {
                Grupos o = (Grupos) object;
                return getStringKey(o.getIdGrupo());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Grupos.class.getName());
            }
        }
    }
}

MagicFinger/MagicFinger-war/web/profesor/grupos/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Agregar Grupos</title>
        <link href="/MagicFinger-war/faces/resources/css/default.css" rel="stylesheet" type="text/css" />
        <link href="/MagicFinger-war/faces/resources/css/cssLayout.css" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" type="text/css" href="/MagicFinger-war/faces/jsfcrud.css" />

    </h:head>
    <h:body>
        <div id="top" style="display: inline-block; text-align: center">
            <div id="logo" style="display: inline-block; float:left">
                <h:form>
                 <h:commandLink action="/faces/profesor/index.xhtml">
                            <img src="/MagicFinger-war/faces/img/MagicFinger.png" style="padding: 5px" height="40" width="150" />
                 </h:commandLink>
                </h:form>
            </div>
            <div id="hora" style="display: inline-block;vertical-align: middle; margin-top: 17px">
                <p:clock pattern="dd.MM.yy HH.mm" mode="server"/>
            </div>
            <div style="display: inline-block;float: right;margin-top:10px">
                <h:form id="form" prependId="false">
                    <div style="display: inline-block;vertical-align: middle"><p:outputLabel value="#{loginSessionMB.profesor.toString()}"/></div>
                    
                    <div style="display: inline-block;width: 50px;vertical-align: middle">
                        <p:commandLink action="#{loginMB.logout()}" value="Cerrar sesión">
                            <p:confirm header="Confirmación" message="¿Desea cerrar sesión?" icon="ui-icon-alert" />  
                        </p:commandLink>
                        <p:confirmDialog global="true" showEffect="explode" hideEffect="explode">  
                            <p:commandButton style="margin-left:10%;" value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"/>  
                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>       
                        </p:confirmDialog>
                    </div>
                </h:form>
            </div>
        </div>      
        <div class="center_content">
            <h1 style="margin-bottom: 20px;font-family: -webkit-pictograph;">
                <span>Agregar grupo</span> 
                <span style="float: right"> #{postLoginMB.nombreUniversidad} <span style="font: menu">
                    <h:outputLink value="/MagicFinger-war/faces/administrador/index.xhtml" >
                         [Cambiar]
                    </h:outputLink>
                    </span> 
                </span> 
                </h1>
            <h:form><p:growl id="grow1" showDetail="true" />
                <div style="text-align:center">
                    
                    <div style="text-align: left; display: inline-block;width: 100%; margin-bottom: 20px;" >
                        
                    </div>
                    <div id="agregar" style="display: inline-block;width: 100%;">
                    <img src="/MagicFinger-war/faces/img/advertencia.png" height="24" width="26" style="vertical-align: middle"/>
                    <p style="vertical-align: middle;display: inline-block;text-align: center">
                        Para agregar un grupo, debe completar los siguientes datos:
                    </p>
                    </div>
                    <div style="display:inline-block;border-width: 1px ;border-radius: 10px ;border-style: dashed; border-color: gray; width: 600px;text-align: center;margin-top: 10px ">
                        <h:panelGrid columns="2" style="margin: 0 auto; padding: 10px;">
                            <h4 style="display: inline-block;"> <p:outputLabel style="vertical-align: center" value="#{bundle.CreateGruposLabel_nombre}" for="nombre" />
                            </h4>
                            <p:inputText style="vertical-align: center" id="nombre" value="#{gruposController.selected.nombre}"/>

                           
                        </h:panelGrid>
                        <p:commandLink style="display: inline-block; margin-right: 25px" action="#{gruposController.create}">
                            <img src="/MagicFinger-war/faces/img/ok.png" width="38" height="32" style="margin: 0 auto;display:block"/>
                            <p:outputLabel> Guardar grupo</p:outputLabel>
                        </p:commandLink>
                        <p:commandLink style="display: inline-block;" action="/faces/profesor/grupos/grupos.xhtml?cid=1" immediate="true">
                            <img src="/MagicFinger-war/faces/img/atras.png" width="38" height="32" style="margin: 0 auto;display:block"/>
                            <p:outputLabel>Volver</p:outputLabel>
                        </p:commandLink>
                        <br></br><br></br>
                    </div>
                </div>
            </h:form>
        </div>
    </h:body>
</html>

MagicFinger/MagicFinger-war/web/profesor/grupos/grupos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="/MagicFinger-war/faces/resources/css/default.css" rel="stylesheet" type="text/css" />
        <link href="/MagicFinger-war/faces/resources/css/cssLayout.css" rel="stylesheet" type="text/css" />
        <title>Grupos</title>
    </h:head>
    <h:body>
        <div id="top" style="display: inline-block; text-align: center">
            
            <div id="logo" style="display: inline-block; float:left">
                <h:form>
                 <h:commandLink action="/faces/profesor/index.xhtml">
                            <img src="/MagicFinger-war/faces/img/MagicFinger.png" style="padding: 5px" height="40" width="150" />
                 </h:commandLink>
                </h:form>
            </div>
            <div id="hora" style="display: inline-block;vertical-align: middle; margin-top: 17px">
                <p:clock pattern="dd.MM.yy HH.mm" mode="server"/>
            </div>
            <div style="display: inline-block;float: right;margin-top:10px">
                <h:form id="forem" prependId="false">
                    <div style="display: inline-block;vertical-align: middle"><p:outputLabel value="#{loginSessionMB.profesor.toString()}"/></div>
                    
                    <div style="display: inline-block;width: 50px;vertical-align: middle">
                        <p:commandLink action="#{loginMB.logout()}" value="Cerrar sesión">
                            <p:confirm header="Confirmación" message="¿Desea cerrar sesión?" icon="ui-icon-alert" />  
                        </p:commandLink>
                        <p:confirmDialog global="true" showEffect="explode" hideEffect="explode">  
                            <p:commandButton style="margin-left:10%;" value="Si" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check"/>  
                        <p:commandButton value="No" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close"/>       
                        </p:confirmDialog>
                    </div>
                </h:form>
            </div>  
        </div>
        <div class="center_content">
            <h1 style="margin-bottom: 20px;font-family: -webkit-pictograph;">
                <span>Gestión de grupos</span> 
                <span style="float: right"> #{postLoginMB.nombreUniversidad} <span style="font: menu">
                    <h:outputLink value="/MagicFinger-war/faces/profesor/index.xhtml" >
                         [Cambiar]
                    </h:outputLink>
                    </span> 
                </span> 
            </h1>
            <h:form id="form" > <p:growl id="grow1" showDetail="true" />
                <div style="text-align: center">
                    
                    <div id="agregar" style="display: inline-block;width: 100%;">
                        <img src="/MagicFinger-war/faces/img/advertencia.png" height="24" width="26" style="vertical-align: middle"/>
                        <p style="vertical-align: middle;display: inline-block;text-align: center">
                            Para agregar un grupo, debe completar los siguientes datos:
                        </p>
                        
                        <h:commandLink action="#{gruposController.prepareCreate}" style="display: inline-block;float: right">
                            <img src="/MagicFinger-war/faces/img/agregar.png" style="margin: 0 auto;display: block;"/>
                            <h:outputLabel>Agregar Grupos</h:outputLabel>
                        </h:commandLink>
                        <h:commandLink action="/faces/profesor/index2.xhtml" style="display: inline-block;float: right;margin-right: 20px">
                            <img src="/MagicFinger-war/faces/img/atras.png" width="38" height="37" style="margin: 0 auto;display:block"/>
                            <h:outputLabel>Volver</h:outputLabel>
                        </h:commandLink>
                        
                    </div>

                        <div style="margin-bottom: 20px;display:inline-block;border-width: 1px ;border-radius: 10px ;border-style: dashed; border-color: gray; width: 600px;text-align: center;margin-top: 10px">
                        <div style="display: inline-block; text-align: center">
                            <p:dataTable id="grupo" 
                                     style="width: 330px;margin-top:20px; display: inline-block;text-align: center;margin-bottom: 35px" 
                                     var="gru" value="#{gruposMB.listaGrupoData}" 
                                     selection ="#{gruposMB.grupoSeleccionado}"
                                     selectionMode="single"
                                     >  
                            <p:ajax event="rowSelect" listener="#{gruposMB.onRowSelect}"
                                    update=":form:grow1 :form:pickList :form:grupo"/> 

                            <p:column headerText="Nombre Grupos" style="width:50%" >  
                                <h:outputText value="#{gru.toString()}" />  
                            </p:column>
                            <p:column style="text-align: center;">
                            <f:facet name="header">
                                <h:outputText value="Acciones"/>
                            </f:facet>
                            <h:commandLink action="#{gruposController.prepareView(gru)}">
                                <img src="/MagicFinger-war/faces/img/ojo.png" style="margin-left: 10px" height="17" width="17" />
                            </h:commandLink>
                            <h:commandLink action="#{gruposController.prepareEdit(gru)}">
                                <img src="/MagicFinger-war/faces/img/editar.png" style="margin-left: 15px" height="17" width="17" />
                            </h:commandLink>
                            <h:commandLink action="#{gruposController.destroy(gru)}">
                                <img src="/MagicFinger-war/faces/img/eliminar.png" style="margin-left: 15px;margin-right: 10px" height="17" width="17" />
                            </h:commandLink>
                        </p:column>
                        </p:dataTable>
                        <p:pickList style="width: 400px;margin: 0 auto; padding: 10px; text-align: left" id="pickList" value="#{gruposMB.asignar}" var="city" itemLabel="#{city}" itemValue="#{city.getAlumno().getIdAlumno()}" showCheckbox="true" showSourceFilter="true" showTargetFilter="true">  
                        <f:facet name="sourceCaption">Alumnos Disponibles</f:facet>  
                        <f:facet name="targetCaption">Integrantes</f:facet>
                        <p:ajax event="transfer" listener="#{gruposMB.onTransfer}" update=":form:grow1" /> 
                        </p:pickList>
                        </div>
                        </div>
                </div>
           </h:form>
        </div>
    </h:body>
</html>
